version: "3.9"
services:
  # trackmyticket-database
  trackmyticket-database:
    image: postgres:latest
    container_name: trackmyticket-database
    hostname: trackmyticket-database
    environment:
      - POSTGRES_USER=trackmyticketuser
      - POSTGRES_PASSWORD=71B4D8X0PPQUNzFm
      - POSTGRES_DB=trackmyticket
    restart: always

  # Backend Application
  trackmyticketserver:
     depends_on:
       trackmyticket-database:
         condition: service_started
     image: trackmyticketserver
     container_name: trackmyticketserver
     build:
       dockerfile: Dockerfile
     ports:
       - "8081"
     environment:
       - MONGO_DB_CONN=postgresql://schafkopf-database:5432/schafkopf
       - REACT_APP_URI=https://my-tickets.netlify.app
       - JWT_SECRET=xlrFQOo6ka0zrCh6GcebT5dvbjkb2cUS
     restart: always
