name: Deploy on AlpineWeezl-Server

on:
  pull_request:
    types: close
  push:
    branches: main

jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
#    - name: install latest npm lts
#      run: nvm install --lts
      
#    - name: use latest npm lts
#      run: nvm use --lts

    - name: check node version
      run: node --version

    - name: get npm packages
      run: npm i

    - name: Build Docker image
      run: docker compose -f docker-compose.yml up -d
    
