name: Deploy on AlpineWeezl-Server

on:
  pull_request:
    types: close
  push:
    branches: main

jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: install nvm version manager
      run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    
    - name: install latest npm lts
      run: nvm install --lts
      
    - name: use latest npm lts
      run: nvm use --lts

    - name: get npm packages
      run: npm i

    - name: Build Docker image
      run: docker compose -f docker-compose.yml up -d
    
